extensions:
  workfront/ui/1:
    $include: src/workfront-ui-1/ext.config.yaml
    runtimeManifest:
      packages:
        heineken:
          license: Apache-2.0
          actions:
            wfapi:
              function: src/workfront-ui-1/actions/wfapi/index.js
              web: 'yes'
              runtime: nodejs:22
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
